name: Android

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
    - run: ./gradlew assembleRelease

