name: Cordova

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        working-directory: cordova-plugin-genius-scan-demo
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm install -g cordova
    - run: cordova prepare
#    - run: cordova build ios
    - run: cordova build android
    - run: cordova build android --release -- --packageType=apk
    - run: du -h platforms/android/app/build/outputs/apk/debug/app-debug.apk
    - run: du -h platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
