name: Cordova

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - '**'

jobs:
  build-android:
    runs-on: macos-14
    defaults:
      run:
        working-directory: cordova-plugin-genius-scan-demo
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Setup Android SDK
      uses: amyu/setup-android@v4
      with:
        ndk-version: 26.2.11394342
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install -g cordova
    - run: npm i
    - run: npx patch-package
    - run: cordova prepare
    - run: cordova build android
    - run: du -h platforms/android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    runs-on: macos-14
    defaults:
      run:
        working-directory: cordova-plugin-genius-scan-demo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g cordova
      - run: npm i
      - run: cordova prepare
      - run: cordova build ios
