name: Cordova

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - upload-dsym

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        working-directory: cordova-plugin-genius-scan-demo
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: actions/setup-node@v4
      with:
        node-version: 19
    - run: npm install -g cordova
    - run: cordova prepare
    - run: cordova build
