name: Flutter

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - '**'

defaults:
  run:
    working-directory: flutter-plugin-genius-scan-demo

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.x'
    - run: flutter pub get
    - run: flutter build apk
  ios:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.x'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
