name: iOS

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - '**'

jobs:
  build-custom-demo:
    runs-on: macos-14
    defaults:
      run:
        working-directory: ios/GSSDKCustomDemo
    steps:
    - uses: actions/checkout@v4
    - run: xcodebuild build -scheme GSSDKCustomDemo -workspace GSSDKCustomDemo.xcworkspace -configuration Debug -sdk iphoneos \
           ONLY_ACTIVE_ARCH=YES \
           CODE_SIGNING_ALLOWED="NO"
  build-simple-demo:
    runs-on: macos-14
    defaults:
      run:
        working-directory: ios/GSSDKSimpleDemo
    steps:
    - uses: actions/checkout@v4
    - run: xcodebuild build -scheme GSSDKSimpleDemo -workspace GSSDKSimpleDemo.xcworkspace -configuration Debug -sdk iphoneos \
           ONLY_ACTIVE_ARCH=YES \
           CODE_SIGNING_ALLOWED="NO"
