name: ReactNative

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - '**'

defaults:
  run:
    working-directory: react-native-genius-scan-demo

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17
    - uses: actions/setup-node@v4
    - run: npm install
    - run: cd android && ./gradlew assembleRelease
  ios:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: npm install
    - run: cd ios && pod install
    - run: cd ios && xcodebuild archive -workspace demo.xcworkspace -scheme demo CODE_SIGNING_ALLOWED=NO
