name: Xamarin

# Note: using the `branches` selector excludes all tags
on:
  push:
    branches:
      - '**'

jobs:
  android:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: Android
      run: |
        cd xamarin
        nuget restore
        cd SimpleDemo.Forms.Android
        msbuild SimpleDemo.Forms.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug

  ios:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: iOS
      run: |
        cd xamarin
        nuget restore
        msbuild SimpleDemo.Forms.iOS/SimpleDemo.Forms.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
